### ISSUE TITLE
Incorporate Oxford Covid government response tracker data

### ISSUE THREAD

**Issue by cportner** [population-research/uganda-covid#30]
The main website is https://www.bsg.ox.ac.uk/research/research-projects/covid-19-government-response-tracker and their GitHub page is https://github.com/OxCGRT/covid-policy-tracker

- [x] Figure out if we can get the individual indicators for Uganda over time
- [x] Download and recast to per month
- [ ] ~~Merge into main data~~

Punting on the merge into main data until we have decided how best to use the data.
